"""users 0002 onboarding+prefs+gamif

Revision ID: 5beafcc06e5f
Revises: c86eb0c1dbdb
Create Date: 2025-11-15 22:26:36.337457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5beafcc06e5f'
down_revision: Union[str, Sequence[str], None] = 'c86eb0c1dbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('class_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('subjects', sa.JSON(), nullable=False))
    op.add_column('users', sa.Column('weekly_target_min', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('work_min', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('break_min', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('rounds', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('xp_total', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_study_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('trial_end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'trial_end_at')
    op.drop_column('users', 'plan')
    op.drop_column('users', 'last_study_at')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'xp_total')
    op.drop_column('users', 'rounds')
    op.drop_column('users', 'break_min')
    op.drop_column('users', 'work_min')
    op.drop_column('users', 'weekly_target_min')
    op.drop_column('users', 'subjects')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'class_level')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
