"""users_0002_onboarding

Revision ID: 9040f3556fd3
Revises: 5beafcc06e5f
Create Date: 2025-11-16 16:01:29.223043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9040f3556fd3'
down_revision: Union[str, Sequence[str], None] = '5beafcc06e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_goal', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('onboarding_done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_done')
    op.drop_column('users', 'main_goal')
    # ### end Alembic commands ###
